<?php 
class CacherSchema extends CakeSchema {

	public function before($event = array()) {
		return true;
	}

	public function after($event = array()) {
	}
 
	public $cacher_queries = array(
		'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 20, 'key' => 'primary'),
		'model_name' => array('type' => 'string', 'null' => false, 'length' => 100, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'model_alias' => array('type' => 'string', 'null' => false, 'length' => 100, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'model_use' => array('type' => 'string', 'null' => false, 'length' => 100, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'model_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20, 'key' => 'index'),
		'query_key' => array('type' => 'string', 'null' => false, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'query' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'querytime' => array('type' => 'float', 'null' => false, 'default' => '0.0', 'length' => '10,4', 'key' => 'index'),
		'path' => array('type' => 'string', 'null' => false, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'recache' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'key' => 'index'),
		'recacheerror' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'key' => 'index'),
		'recacheerrormsg' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'created' => array('type' => 'datetime', 'null' => true, 'default' => null),
		'modified' => array('type' => 'datetime', 'null' => true, 'default' => null),
		'lastran' => array('type' => 'datetime', 'null' => true, 'default' => null),
		'recached' => array('type' => 'datetime', 'null' => true, 'default' => null),
		'requested' => array('type' => 'datetime', 'null' => true, 'default' => null),
		'indexes' => array(
			'PRIMARY' => array('column' => 'id', 'unique' => 1),
			'model_name' => array('column' => 'model_name', 'unique' => 0),
			'model_id' => array('column' => 'model_id', 'unique' => 0),
			'recache' => array('column' => 'recache', 'unique' => 0),
			'model_alias' => array('column' => 'model_alias', 'unique' => 0)
		),
		'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB')
	);
 
	public $memcache_servers = array(
		'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 20, 'key' => 'primary'),
		'hosthash' => array('type' => 'string', 'null' => false, 'default' => '', 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'host' => array('type' => 'string', 'null' => false, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'port' => array('type' => 'string', 'null' => false, 'length' => 15, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'pid' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'uptime' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'version' => array('type' => 'string', 'null' => false, 'default' => '', 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'libevent' => array('type' => 'string', 'null' => false, 'default' => '', 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'rusage_user' => array('type' => 'float', 'null' => false, 'default' => '0.0', 'length' => '10,4'),
		'rusage_system' => array('type' => 'float', 'null' => false, 'default' => '0.0', 'length' => '10,4'),
		'pointer_size' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'curr_connections' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'total_connections' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'connection_structures' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'reserved_fds' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cmd_get' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cmd_set' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cmd_flush' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cmd_touch' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'get_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'get_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'delete_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'delete_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'incr_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'incr_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'decr_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'decr_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cas_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cas_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cas_badval' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'touch_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'touch_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'auth_cmds' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'auth_errors' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'bytes_read' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'bytes_written' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'limit_maxbytes' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'accepting_conns' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'key' => 'index'),
		'listen_disabled_num' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'threads' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
		'conn_yields' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'hash_power_level' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5),
		'hash_bytes' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'hash_is_expanding' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'key' => 'index'),
		'expired_unfetched' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'evicted_unfetched' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'bytes' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'curr_items' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'total_items' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'evictions' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'reclaimed' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'created' => array('type' => 'datetime', 'null' => true, 'default' => null),
		'modified' => array('type' => 'datetime', 'null' => true, 'default' => null),
		'indexes' => array(
			'PRIMARY' => array('column' => 'id', 'unique' => 1),
			'hosthash' => array('column' => 'hosthash', 'unique' => 0),
			'host' => array('column' => 'host', 'unique' => 0),
			'port' => array('column' => 'port', 'unique' => 0),
			'pid' => array('column' => 'pid', 'unique' => 0),
			'version' => array('column' => 'version', 'unique' => 0),
		),
		'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB')
	);
 
	public $memcache_server_logs = array(
		'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 20, 'key' => 'primary'),
		'memcache_server_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20, 'key' => 'index'),
		'pid' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'uptime' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'version' => array('type' => 'string', 'null' => false, 'default' => '', 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'libevent' => array('type' => 'string', 'null' => false, 'default' => '', 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
		'rusage_user' => array('type' => 'float', 'null' => false, 'default' => '0.0', 'length' => '10,4'),
		'rusage_system' => array('type' => 'float', 'null' => false, 'default' => '0.0', 'length' => '10,4'),
		'pointer_size' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'curr_connections' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'total_connections' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'connection_structures' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'reserved_fds' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cmd_get' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cmd_set' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cmd_flush' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cmd_touch' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'get_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'get_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'delete_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'delete_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'incr_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'incr_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'decr_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'decr_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cas_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cas_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'cas_badval' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'touch_hits' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'touch_misses' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'auth_cmds' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'auth_errors' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'bytes_read' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'bytes_written' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'limit_maxbytes' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'accepting_conns' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'key' => 'index'),
		'listen_disabled_num' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'threads' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
		'conn_yields' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'hash_power_level' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5),
		'hash_bytes' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'hash_is_expanding' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'key' => 'index'),
		'expired_unfetched' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'evicted_unfetched' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'bytes' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
		'curr_items' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'total_items' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'evictions' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'reclaimed' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
		'created' => array('type' => 'datetime', 'null' => true, 'default' => null),
		'indexes' => array(
			'PRIMARY' => array('column' => 'id', 'unique' => 1),
			'memcache_server_id' => array('column' => 'memcache_server_id', 'unique' => 0),
		),
		'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB')
	);
}
